- id: '1766711584683'
  alias: Notify when Nicholas leaves home
  triggers:
  - entity_id: person.nicholas
    zone: zone.home
    event: leave
    trigger: zone
  actions:
  - data:
      title: Leaving Home
      message: You just left the home zone.
    action: notify.mobile_app_jedi_long
  mode: single
- id: '1766713939072'
  alias: Notify - SABnzbd started download
  description: ''
  triggers:
  - entity_id: sensor.sabnzbd_queue_count
    trigger: state
  conditions:
  - condition: template
    value_template: "{{ trigger.from_state is not none\n   and trigger.to_state is
      not none\n   and trigger.from_state.state | int == 0\n   and trigger.to_state.state
      | int > 0 }}\n"
  actions:
  - data:
      title: "SABnzbd Download Started \U0001F4E5"
      message: 'SABnzbd started downloading {{ trigger.to_state.state | int }} {{
        ''item'' if trigger.to_state.state | int == 1 else ''items'' }}.

        '
    action: notify.mobile_app_jedi_long
  mode: single
- id: '1766967144319'
  alias: Thermostat Hot → Front Light Red
  description: Turn front main light red when Nest setpoint > 70°F
  triggers:
  - entity_id:
    - climate.family_room
    attribute: temperature
    above: 70
    trigger: numeric_state
  actions:
  - data:
      rgb_color:
      - 255
      - 38
      - 0
      brightness_pct: 100
    action: light.turn_on
    target:
      entity_id: light.front_wall_right
  mode: single
- id: '1766969483730'
  alias: Start Christmas Shuffle
  description: ''
  triggers:
  - entity_id: input_boolean.christmas_shuffle_enabled
    to: 'on'
    trigger: state
  actions:
  - action: script.christmas_light_shuffle
    data: {}
  mode: single
- id: '1766970904048'
  alias: Alexa Downstairs Christmas Lights
  description: ''
  triggers:
  - webhook_id: alexa_downstairs
    trigger: webhook
  actions:
  - target:
      entity_id: input_boolean.christmas_shuffle_enabled
    action: input_boolean.turn_on
  - target:
      entity_id: script.christmas_color_shuffle
    action: script.turn_on
  mode: single
