- id: '1766968328507'
  name: Christmas Lights
  entities:
    light.front_room_left:
      state: 'on'
      brightness: 200
      rgb_color:
      - 255
      - 0
      - 0
    light.front_room_right:
      state: 'on'
      brightness: 200
      rgb_color:
      - 0
      - 180
      - 0
    light.front_wall_left:
      state: 'on'
      brightness: 180
      rgb_color:
      - 255
      - 200
      - 120
    light.front_wall_right:
      state: 'on'
      brightness: 200
      rgb_color:
      - 255
      - 0
      - 0
    light.main_room_left:
      state: 'on'
      brightness: 200
      rgb_color:
      - 0
      - 180
      - 0
    light.main_room_middle:
      state: 'on'
      brightness: 180
      rgb_color:
      - 255
      - 200
      - 120
    light.main_room_right:
      state: 'on'
      brightness: 200
      rgb_color:
      - 255
      - 0
      - 0
    light.main_wall_left:
      state: 'on'
      brightness: 200
      rgb_color:
      - 0
      - 180
      - 0
    light.main_wall_middle:
      state: 'on'
      brightness: 180
      rgb_color:
      - 255
      - 200
      - 120
    light.main_wall_right:
      state: 'on'
      brightness: 200
      rgb_color:
      - 255
      - 0
      - 0
  icon: mdi:string-lights
