[Interface]
# Key for QNAP-Gluetun
# Bouncing = 3
# NetShield = 1
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = uPUFvXTPbP/iM7g2o/ZARX0wwWf8O4iX6wfQDN1bDl8=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# NL-FREE#120
PublicKey = TH87YVmOQBoo1Mir13INlDzvTOlvsi9dWmAp+IF3bRg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.34.244.169:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:c041:2347::10]:51820
PersistentKeepalive = 25
